// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUND66Cw5oLw0rZkxQ8RufaKROZDt1YxY',
    appId: '1:253312907233:web:0fb4686b348381f65904a0',
    messagingSenderId: '253312907233',
    projectId: 'fire-chat-c7e2c',
    authDomain: 'fire-chat-c7e2c.firebaseapp.com',
    storageBucket: 'fire-chat-c7e2c.appspot.com',
    measurementId: 'G-4WPE8N6Z5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFcXnNXyfEMoF0AGz22i0i--PPQ9Umgg',
    appId: '1:253312907233:android:1a0fbc48ee676f485904a0',
    messagingSenderId: '253312907233',
    projectId: 'fire-chat-c7e2c',
    storageBucket: 'fire-chat-c7e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVO547UWod4dbBRdjBTtdCNg7w4tTBP9Q',
    appId: '1:253312907233:ios:aff42531edd517ef5904a0',
    messagingSenderId: '253312907233',
    projectId: 'fire-chat-c7e2c',
    storageBucket: 'fire-chat-c7e2c.appspot.com',
    iosBundleId: 'com.example.remoteCollabTool',
  );
}
